// Optional browser acceptance test. Requires playwright-core and a Chromium executable.
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { startMock } from './mock-provider.mjs';
import { createApp } from '../src/server.mjs';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ? pathToFileURL(process.env.PLAYWRIGHT_MODULE).href : 'playwright-core');
const dir = await mkdtemp(join(tmpdir(), 'humanizer-ui-'));
const mock = await startMock(); const app = await createApp({ dataDir: dir });
await new Promise((resolve, reject) => { app.once('error', reject); app.listen(0, '127.0.0.1', resolve); });
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH, headless: true, args: ['--no-sandbox'] });
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1050 }, permissions: ['clipboard-read', 'clipboard-write'] });
  const page = await context.newPage(); const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const origin = `http://127.0.0.1:${app.address().port}`;
  const external = []; page.on('request', req => { if (!req.url().startsWith(origin) && !req.url().startsWith('data:')) external.push(req.url()); });
  await page.goto(origin);
  await page.getByRole('heading', { name: 'Connect your LLM.' }).waitFor();
  await page.screenshot({ path: 'docs/screenshots/connect.png', fullPage: true });
  await page.locator('#onboarding').getByLabel('Base URL', { exact: true }).fill(mock.url);
  await page.getByRole('button', { name: 'Connect', exact: false }).click();
  await page.getByLabel('Original text', { exact: true }).waitFor();
  assert.deepEqual(await page.locator('#model-select option').allTextContents(), ['local-editor']);
  const original = 'It is important to note that our system served 50,000 users in 2026.\n\nRead [the documentation](https://example.test/docs) or contact hello@example.test.';
  await page.getByLabel('Original text', { exact: true }).fill(original);
  await page.getByRole('button', { name: 'Humanize', exact: false }).click();
  await page.getByText('Local checks passed', { exact: true }).waitFor();
  assert.equal(await page.getByLabel('Humanized text', { exact: true }).inputValue(), original.replace('It is important to note that ', ''));
  await page.getByRole('button', { name: 'Copy', exact: true }).click();
  await page.getByText('Copied', { exact: true }).waitFor();
  await page.locator('#writing-notes summary').click();
  assert.equal(await page.locator('#writing-notes-rows tr').count(), 5);
  assert.match(await page.locator('#writing-skills-used').textContent(), /Natural writing/);
  await page.screenshot({ path: 'docs/screenshots/writing-notes.png', fullPage: true });
  await page.locator('#writing-notes summary').click();
  await page.screenshot({ path: 'docs/screenshots/workspace.png', fullPage: true });
  await page.getByLabel('Tone', { exact: true }).selectOption('Natural');
  await page.getByLabel('Extra editor review', { exact: true }).check();
  const reviewCalls = mock.state.calls.length;
  await page.getByRole('button', { name: 'Humanize', exact: false }).click();
  await page.getByText(/Extra editor review completed/).waitFor();
  assert.equal(mock.state.calls.length - reviewCalls, 2);
  assert.equal(await page.getByLabel('Humanized text', { exact: true }).inputValue(), original.replace('It is important to note that ', ''));
  await page.reload();
  await page.getByLabel('Original text', { exact: true }).waitFor();
  assert.equal(await page.getByLabel('Tone', { exact: true }).inputValue(), 'Natural');
  assert.equal(await page.getByLabel('Extra editor review', { exact: true }).isChecked(), true);
  await page.getByLabel('Original text', { exact: true }).fill(original);
  await page.getByLabel('Extra editor review', { exact: true }).uncheck();
  await page.screenshot({ path: 'docs/screenshots/natural-review.png', fullPage: true });
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  await page.getByRole('button', { name: 'Test Connection', exact: true }).click();
  await page.getByText('Connected · 2 models found. Connection not saved yet.', { exact: true }).waitFor();
  await page.getByRole('switch', { name: 'Enable text-embedding', exact: true }).check();
  await page.waitForFunction(() => document.querySelector('#model-select').options.length === 2);
  await page.getByRole('switch', { name: 'Enable local-editor', exact: true }).uncheck();
  await page.waitForFunction(() => document.querySelector('#model-select').options.length === 1);
  mock.state.models.push({ id: 'second-chat' });
  await page.getByRole('button', { name: 'Refresh Models', exact: true }).click();
  await page.getByText('3 models found. Your model preferences were kept.', { exact: true }).waitFor();
  assert.equal(await page.getByRole('switch', { name: 'Enable local-editor', exact: true }).isChecked(), false);
  await page.getByRole('switch', { name: 'Enable local-editor', exact: true }).check();
  await page.waitForFunction(() => document.querySelector('#model-select').options.length === 3);
  await page.getByRole('switch', { name: 'Enable text-embedding', exact: true }).uncheck();
  await page.waitForFunction(() => document.querySelector('#model-select').options.length === 2);
  await page.getByLabel('Temperature', { exact: true }).fill('0.5');
  await page.getByLabel('Protected names & terms', { exact: false }).fill('Ayşe Yılmaz\nAcme Corp');
  await page.getByRole('button', { name: 'Save preferences', exact: true }).click();
  await page.getByText('Preferences saved.', { exact: true }).waitFor();
  await page.getByRole('switch', { name: 'Enable skill Natural writing', exact: true }).waitFor();
  assert.equal(await page.getByRole('switch', { name: 'Enable skill Natural writing', exact: true }).isChecked(), true);
  assert.equal(await page.getByRole('switch', { name: 'Enable skill Türkçe açıklık', exact: true }).isChecked(), true);
  await page.getByRole('switch', { name: 'Enable skill Structure & clarity', exact: true }).check();
  await page.getByText('3 / 3 enabled', { exact: true }).waitFor();
  await page.getByRole('switch', { name: 'Enable skill Voice & rhythm', exact: true }).check();
  await page.getByText('Enable at most 3 skills at once.', { exact: true }).waitFor();
  assert.equal(await page.getByRole('switch', { name: 'Enable skill Voice & rhythm', exact: true }).isChecked(), false);
  await page.getByRole('switch', { name: 'Enable skill Structure & clarity', exact: true }).uncheck();
  await page.getByText('2 / 3 enabled', { exact: true }).waitFor();
  await page.locator('#skill-import-panel > summary').click();
  const markdown = '---\nname: support-voice\ndescription: Edit support messages.\n---\nUse concrete verbs and preserve all facts.';
  await page.getByLabel('SKILL.md file', { exact: false }).setInputFiles({ name: 'SKILL.md', mimeType: 'text/markdown', buffer: Buffer.from(markdown) });
  await page.waitForFunction(() => document.querySelector('#skill-markdown').value.includes('support-voice'));
  await page.getByRole('button', { name: 'Preview skill', exact: true }).click();
  await page.locator('#skill-preview-name').getByText('support-voice', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Import skill', exact: true }).click();
  await page.getByRole('switch', { name: 'Enable skill support-voice', exact: true }).waitFor();
  assert.equal(await page.getByRole('switch', { name: 'Enable skill support-voice', exact: true }).isChecked(), false);
  await page.getByRole('switch', { name: 'Enable skill support-voice', exact: true }).check();
  await page.getByText('3 / 3 enabled', { exact: true }).waitFor();
  await page.locator('#skills-title').scrollIntoViewIfNeeded();
  await page.screenshot({ path: 'docs/screenshots/skills.png', fullPage: true });
  const packDownload = page.waitForEvent('download');
  await page.getByRole('link', { name: 'Download all 4 skills + source licenses ↓', exact: true }).click();
  assert.equal((await packDownload).suggestedFilename(), 'humanizer-skills.zip');
  await page.locator('#settings-dialog').evaluate(element => { element.scrollTop = 0; });
  await page.screenshot({ path: 'docs/screenshots/settings.png', fullPage: true });
  await page.getByRole('button', { name: 'Close settings', exact: true }).click();
  await page.getByLabel('Model', { exact: true }).selectOption('local-editor');
  mock.state.mode = 'facts';
  await page.getByRole('button', { name: 'Humanize', exact: false }).click();
  await page.getByText(/Fact preservation check failed/).waitFor();
  assert.equal(await page.getByLabel('Humanized text', { exact: true }).inputValue(), '');
  assert.equal(await page.getByLabel('Original text', { exact: true }).inputValue(), original);
  mock.state.mode = 'slow';
  await page.getByRole('button', { name: 'Humanize', exact: false }).click();
  await page.getByRole('button', { name: 'Stop', exact: true }).click();
  await page.getByText(/Stopped. Your original text is unchanged/).waitFor();
  mock.state.mode = 'stream';
  await page.reload();
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  assert.equal(await page.getByLabel('Temperature', { exact: true }).inputValue(), '0.5');
  await page.getByRole('switch', { name: 'Enable skill support-voice', exact: true }).waitFor();
  assert.equal(await page.getByRole('switch', { name: 'Enable skill support-voice', exact: true }).isChecked(), true);
  await page.getByRole('button', { name: 'Remove skill support-voice', exact: true }).click();
  await page.getByText('Custom skill removed.', { exact: true }).waitFor();
  assert.equal(await page.getByRole('switch', { name: 'Enable skill support-voice', exact: true }).count(), 0);
  assert.equal(await page.getByLabel('Protected names & terms', { exact: false }).inputValue(), 'Ayşe Yılmaz\nAcme Corp');
  await page.getByRole('button', { name: 'Close settings', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'docs/screenshots/mobile.png', fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  assert.deepEqual(errors, []); assert.deepEqual(external, []);
  console.log('Browser acceptance passed: onboarding, discovery, rewrite, copy, model toggles/refresh, preferences, fact failure, stop, reload, mobile, skill selection/limits/import/preview/download/delete/persistence, writing notes, no external requests.');
} finally {
  await browser.close(); await mock.close();
  await new Promise(resolve => { app.close(resolve); app.closeAllConnections(); }); await rm(dir, { recursive: true, force: true });
}
